### PR TITLE
Add Table Tests of Batch

### PR DESCRIPTION
**Pull request by zzhxiaofeng**
Add following tests of table batch: 
- Batch with group of Insert Or Replace Entity
- Batch with group of Insert Or Merge Entity 
- Batch with combined between Insert Entity & Update Entity
- Batch with combined between Insert Entity & Merge Entity
- Batch with combined between Insert Entity & Delete Entity

Please have a look when you are free and tell me if there are some questions.

### CODE REVIEW

**Comment by edwin-huber** [comment]
Hi  @zzhxiaofeng many thanks for this.
Can you take a look at https://github.com/Azure/Azurite/pull/691 and rebase off that, or submit directly there?
I don't want your 🥇  contributions to be lost in my mess 😉

**Comment by edwin-huber** [comment]
I have a new branch called batch_v1 which I use here

**Comment by zzhxiaofeng** [comment]
@edwin-huber Ok, I have changed to your new branch batch_v1, please have a look when you are free.

**Comment by edwin-huber** [comment]
Looks good 🥇

**Review by edwin-huber — APPROVED** [review]
LGTM 👍

**Pull request merged**
